### ISSUE TITLE
Seems to work, but pops up empty Chrome window and no code.

### ISSUE THREAD

**Issue by Davegeo** [inAudible-NG/audible-activator#26]
I'm running this on a Mac, with Selenium, Requests, Chromedriver all installed, but all it does when I run it is pop up an empty Chrome window with data:, as the url and the following after the Player ID:

Traceback (most recent call last):
  File "./audible-activator.py", line 145, in <module>
    fetch_activation_bytes(username, password, options)
  File "./audible-activator.py", line 54, in fetch_activation_bytes
    executable_path=chromedriver_path)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 408, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 440, in _request
    resp = self._conn.getresponse()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

What would you suggest?

**Comment by inAudible-NG** [comment]
Something seems broken with your local setup. It's hard to tell what exactly is wrong though.

Try using https://github.com/inAudible-NG/tables to recover "activation_bytes" in an offline manner.

**Comment by Davegeo** [comment]
That's excellent - worked brilliantly, thank you very much.
