### ISSUE TITLE
.co.uk lang not working

### ISSUE THREAD

**Issue by kukoman** [inAudible-NG/audible-activator#32]
Hi There,

Thanks for the tool. I'm trying to use it with audible.co.uk /amazon.co.uk but it doesn't work - I always end up on amazon page "Looking for Something?". It can open the audible website, injects the credentials and then it hangs on the amazon page... 

Any hints or anyone have logged in successfully on .co.uk? 

(I tried with -l co.uk, replaced all .com in the /audible-activator.py script but still no luck)

Thanks

**Comment by kukoman** [comment]
Traceback (most recent call last):
  File "./audible-activator.py", line 148, in <module>
    fetch_activation_bytes(username, password, options)
  File "./audible-activator.py", line 67, in fetch_activation_bytes
    search_box = driver.find_element_by_id('ap_email')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 285, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 787, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"ap_email"}
  (Session info: chrome=58.0.3029.96)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.9.0-0.bpo.1-amd64 x86_64)

**Comment by inAudible-NG** [comment]
`co.uk` has never been officially tested nor supported.

I recommend using https://github.com/inAudible-NG/tables instead of this project.

**Comment by inAudible-NG** [comment]
Latest commit has untested support for `co.uk` but using https://github.com/inAudible-NG/tables is recommended.
