### ISSUE TITLE
Failed to establish new connection

### ISSUE THREAD

**Issue by hongkongkiwi** [inAudible-NG/audible-activator#33]
I tried the latest code both in debug mode and normal mode, here's the results

```
Username: me@example.com
Password:
[*] Player ID is SOME_LONG_ID_HERE=
Traceback (most recent call last):
  File "./audible-activator.py", line 160, in <module>
    fetch_activation_bytes(username, password, options)
  File "./audible-activator.py", line 99, in fetch_activation_bytes
    s.get(durl, headers=headers)
  File "/Users/andy/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Users/andy/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/andy/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/andy/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.audible.com', port=443): Max retries exceeded with url: /license/licenseForCustomerToken?customer_token=LONG_STRING_HERE=&action=de-register (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10f0f8590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

I'm using Mac OSX.

**Comment by hongkongkiwi** [comment]
In the end I got my audible activation bytes using ffprobe your rainbow hash tables! Thanks :-)

**Comment by inAudible-NG** [comment]
The stack trace indicates a network issue on the client side.

I am glad to hear that https://github.com/inAudible-NG/tables/ worked well for you 👍
