### ISSUE TITLE
Operation not permitted: 'activation.blob'

### ISSUE THREAD

**Issue by dampus200** [inAudible-NG/audible-activator#35]
I get a strange error right at the end which I cannot understand. Any ideas that's going on?
Thanks.

```
Traceback (most recent call last):
  File "/Users//Downloads/audible-activator-master/audible-activator.py", line 160, in <module>
    fetch_activation_bytes(username, password, options)
  File "/Users//Downloads/audible-activator-master/audible-activator.py", line 106, in fetch_activation_bytes
    with open("activation.blob", "wb") as f:
IOError: [Errno 1] Operation not permitted: 'activation.blob'
```

**Comment by inAudible-NG** [comment]
The error message is clear enough. The current working directory does not seem to be writable for some reason. You will have to figure out why this is so. Try running the script with `/tmp` as the working directory.
